# Generated by Django 3.2.25 on 2025-11-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_date',
            field=models.DateTimeField(blank=True, help_text='Set a reminder for this task', null=True),
        ),
    ]
